// yanlisDogruData.js

const yanlisDogruData = [
  { yanlis: "Eşortman", dogru: "Eşofman" },
  { yanlis: "Ahçı", dogru: "Aşçı" },
  { yanlis: "Herkez", dogru: "Herkes" },
  { yanlis: "İddaa", dogru: "İddia" },
  { yanlis: "Aferim", dogru: "Aferin" },
  { yanlis: "Sürpriz", dogru: "Sürpriz" },
  { yanlis: "Tesbit", dogru: "Tespit" },
  { yanlis: "Yalnış", dogru: "Yanlış" },
  { yanlis: "Şarz", dogru: "Şarj" },
  { yanlis: "Gardolap", dogru: "Gardırop" },
  { yanlis: "Yanlız", dogru: "Yalnız" },
  { yanlis: "Dinazor", dogru: "Dinozor" },
  { yanlis: "Acaip", dogru: "Acayip" },
  { yanlis: "Acenta", dogru: "Acente" },
  { yanlis: "Adele", dogru: "Adale" },
  { yanlis: "Afilli", dogru: "Afili" },
  { yanlis: "Afaroz", dogru: "Aforoz" },
  { yanlis: "Ahlağa", dogru: "Ahlaka" },
  { yanlis: "Acitasyon", dogru: "Ajitasyon" },
  { yanlis: "Akibet", dogru: "Akıbet" },
  { yanlis: "Ankara’lı", dogru: "Ankaralı" },
  { yanlis: "Anfi", dogru: "Amfi" },
  { yanlis: "Ataç", dogru: "Ataş" },
  { yanlis: "Birhaber", dogru: "Bihaber" },
  { yanlis: "Ekzoz", dogru: "Egzoz" },
  { yanlis: "Entellektüel", dogru: "Entelektüel" },
  { yanlis: "Erezyon", dogru: "Erozyon" },
  { yanlis: "İlizyon", dogru: "İllüzyon" },
  { yanlis: "Hoşçakal", dogru: "Hoşça kal" },
  { yanlis: "Sağol", dogru: "Sağ ol" },
  { yanlis: "Mütala", dogru: "Mütaala" },
  { yanlis: "Küsür", dogru: "Küsur" },
  { yanlis: "Harfiyat", dogru: "Hafriyat" },
  { yanlis: "İnsiyatif", dogru: "İnisiyatif" },
  { yanlis: "Ünvan", dogru: "Unvan" },
  { yanlis: "Şöför", dogru: "Şoför" },
  { yanlis: "Şovalye", dogru: "Şövalye" },
  { yanlis: "Asvalt", dogru: "Asfalt" },
  { yanlis: "Cürret", dogru: "Cüret" },
  { yanlis: "İnkilap", dogru: "İnkılap" },
  { yanlis: "İtibariyle", dogru: "İtibarıyla" },
  { yanlis: "Kareografi", dogru: "Koreografi" },
  { yanlis: "Sezeryan", dogru: "Sezaryen" },
  { yanlis: "Vejeteryan", dogru: "Vejetaryen" },
  { yanlis: "Tenefüs", dogru: "Teneffüs" },
  { yanlis: "Peştemal", dogru: "Peştamal" },
  { yanlis: "Müstehak", dogru: "Müstahak" },
  { yanlis: "Menapoz", dogru: "Menopoz" },
  { yanlis: "Komidin", dogru: "Komodin" },
  { yanlis: "Muhattap", dogru: "Muhatap" },
  { yanlis: "Zebze", dogru: "Sebze" },
  { yanlis: "Canbaz", dogru: "Cambaz" },
  { yanlis: "Penbe", dogru: "Pembe" },
  { yanlis: "Çenber", dogru: "Çember" },
  { yanlis: "İskanbil", dogru: "İskambil" },
  { yanlis: "Sarmısak", dogru: "Sarımsa" },
  { yanlis: "Hukuğu", dogru: "Hukuku" },
  { yanlis: "Evrağı", dogru: "Evrakı" },
  { yanlis: "Ateşe", dogru: "Ataşe" },
  { yanlis: "Azerbeycanlı", dogru: "Azeri" },
  { yanlis: "Bilok", dogru: "Blok" },
  { yanlis: "Cumurbaşkanı", dogru: "Cumhurbaşkanı" },
  { yanlis: "Eşşek", dogru: "Eşek" },
  { yanlis: "İskâmbil", dogru: "İskambil" },
  { yanlis: "Karete", dogru: "Karate" },
  { yanlis: "Nâlet", dogru: "Lânet" },
  { yanlis: "Menu", dogru: "Mönü" },
  { yanlis: "Röpörtaj", dogru: "Röportaj" },
];

export default yanlisDogruData;
